name: OCSF Server and OCSF Schema Compiler Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-ocsf-server:
    name: Validate OCSF Server compile of schema
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ocsf-schema
      uses: actions/checkout@v6
    - name: Checkout ocsf-server
      uses: actions/checkout@v6
      with:
        repository: ocsf/ocsf-server
        path: server
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16'  # Define the elixir version [required]
        otp-version: '26'       # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: server/deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install ocsf-server dependencies
      working-directory: server
      run: mix deps.get
    - name: Run ocsf-server tests
      working-directory: server
      run: |
        export SCHEMA_DIR=..
        export SCHEMA_EXTENSION=../extensions
        mix test

  validate-ocsf-schema-compiler:
    name: Validate ocsf-schema-compiler compile of schema
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ocsf-schema
      uses: actions/checkout@v6
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Compile schema
      run: |
        python -m pip install ocsf-schema-compiler
        # Get compiler version
        ocsf-schema-compiler -v
        # Actual output of schema compile is not needed, so pipe to /dev/null
        ocsf-schema-compiler . > /dev/null
