name: Compile Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-ocsf-schema-compiler:
    name: Validate the schema compiles with ocsf-schema-compiler
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ocsf-schema
      uses: actions/checkout@v6
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Compile schema
      run: |
        python -m pip install ocsf-schema-compiler
        # Actual output of schema compile is not needed, so pipe to /dev/null
        ocsf-schema-compiler . > /dev/null
