name: Server Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-ocsf-server:
    name: Validate the schema can be understood by the OCSF server
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ocsf-schema
      uses: actions/checkout@v6
    - name: Checkout ocsf-server
      uses: actions/checkout@v6
      with:
        repository: ocsf/ocsf-server
        path: server
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16'  # Define the elixir version [required]
        otp-version: '26'       # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: server/deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install ocsf-server dependencies
      working-directory: server
      run: mix deps.get
    - name: Run ocsf-server tests
      working-directory: server
      run: |
        export SCHEMA_DIR=..
        export SCHEMA_EXTENSION=../extensions
        mix test
